import streamlit as st
import json
import os
import time
import threading
from http.server import HTTPServer, SimpleHTTPRequestHandler
import socket

# --- PAGE CONFIG ---
st.set_page_config(page_title="Solar Plant Health", layout="wide")

# Start a background HTTP server to serve the JSON file
class DashboardJSONHandler(SimpleHTTPRequestHandler):
    """Simple HTTP handler that only serves dashboard_data.json.

    This prevents directory listing and limits exposure when the server is
    running locally.
    """

    def list_directory(self, path):
        # Disable directory listing
        self.send_error(404, "Directory listing not allowed")
        return None

    def do_GET(self):
        if self.path in ('/', '/dashboard_data.json'):
            self.path = '/dashboard_data.json'
            return super().do_GET()

        # Reject all other paths
        self.send_error(404, "Not Found")


def start_http_server(directory, port=8000):
    handler = lambda *args, **kwargs: DashboardJSONHandler(*args, directory=directory, **kwargs)
    httpd = HTTPServer(('localhost', port), handler)
    print(f"Serving JSON at http://localhost:{port}")
    httpd.serve_forever()

# Check if server is already running
def is_port_open(port):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        result = sock.connect_ex(('localhost', port))
        return result == 0

if not is_port_open(8000):
    server_thread = threading.Thread(target=start_http_server, args=('./extracted_data', 8000), daemon=True)
    server_thread.start()
    time.sleep(1)  # Give server time to start

# Function to load the JSON generated by processor_watchdog.py
def load_data():
    filepath = './extracted_data/dashboard_data.json'
    if os.path.exists(filepath):
        with open(filepath, 'r') as f:
            return json.load(f)
    return None

# --- DASHBOARD UI ---
st.title("☀️ Plant Health & Diagnostic Dashboard")

data = load_data()

if not data:
    st.warning("Waiting for data... Ensure VCOM extraction and Watchdog are running.")
    st.stop()

st.caption(f"Last Data Sync: {data['last_updated']}")

# --- 1. MACRO HEALTH (At a glance) ---
st.header("1. Plant Overview")
cols = st.columns(4)

health = data['macro_health']
cols[0].metric("Total Inverters", health['total_inverters'])
cols[1].metric("🟢 Online & Producing", health['online'])
cols[2].metric("🔴 Tripped (0W)", health['tripped'], delta_color="inverse")
cols[3].metric("🟡 Comms Lost", health['comms_lost'], delta_color="inverse")

st.divider()

# --- 2. EARLY WARNING / ANOMALIES ---
st.header("2. Active Diagnostic Alerts")

anomalies_placeholder = st.empty()

if not data['anomalies']:
    anomalies_placeholder.success("No anomalies detected. Plant is operating nominally.")
else:
    # Separate anomalies by severity for front-end styling
    anomaly_text = ""
    for anomaly in data['anomalies']:
        if anomaly['severity'] == "Critical":
            anomaly_text += f"**CRITICAL: {anomaly['inverter']}** | Type: {anomaly['type']} at {anomaly.get('time', 'N/A')} | Reason: {anomaly['details']}\n\n"
        elif anomaly['severity'] == "High":
            anomaly_text += f"**HIGH: {anomaly['inverter']}** | Type: {anomaly['type']} | Details: {anomaly['details']}\n\n"
        else:
            anomaly_text += f"**NOTICE: {anomaly['inverter']}** | Type: {anomaly['type']} | Details: {anomaly['details']}\n\n"
    anomalies_placeholder.info(anomaly_text)

# Front-end dev notes: 
st.markdown("""
---
*Front-End Dev Note:* 
*To display line charts, point `st.line_chart()` or `plotly` to the processed DataFrames saved in the `./extracted_data/` folder.*
""")

# JavaScript for AJAX polling
js_code = """
<script>
let lastUpdated = '';

function updateDashboard() {
    fetch('http://localhost:8000/dashboard_data.json')
        .then(response => response.json())
        .then(data => {
            if (data.last_updated !== lastUpdated) {
                lastUpdated = data.last_updated;
                // Trigger Streamlit rerun by updating a hidden element or using Streamlit's rerun
                window.location.reload();  // Simple way to refresh
            }
        })
        .catch(error => console.log('Error fetching data:', error));
}

setInterval(updateDashboard, 5000);  // Check every 5 seconds
</script>
"""

st.components.v1.html(js_code, height=0)

# Keep the Python polling as fallback
time.sleep(30)
st.rerun()