import streamlit as st
import json
import os
import time

# --- PAGE CONFIG ---
st.set_page_config(page_title="Solar Plant Health", layout="wide")

# Function to load the JSON generated by processor_watchdog.py
def load_data():
    filepath = './extracted_data/dashboard_data.json'
    if os.path.exists(filepath):
        with open(filepath, 'r') as f:
            return json.load(f)
    return None

# --- DASHBOARD UI ---
st.title("☀️ Plant Health & Diagnostic Dashboard")

data = load_data()

if not data:
    st.warning("Waiting for data... Ensure VCOM extraction and Watchdog are running.")
    st.stop()

st.caption(f"Last Data Sync: {data['last_updated']}")

# --- 1. MACRO HEALTH (At a glance) ---
st.header("1. Plant Overview")
cols = st.columns(4)

health = data['macro_health']
cols[0].metric("Total Inverters", health['total_inverters'])
cols[1].metric("🟢 Online & Producing", health['online'])
cols[2].metric("🔴 Tripped (0W)", health['tripped'], delta_color="inverse")
cols[3].metric("🟡 Comms Lost", health['comms_lost'], delta_color="inverse")

st.divider()

# --- 2. EARLY WARNING / ANOMALIES ---
st.header("2. Active Diagnostic Alerts")

if not data['anomalies']:
    st.success("No anomalies detected. Plant is operating nominally.")
else:
    # Separate anomalies by severity for front-end styling
    for anomaly in data['anomalies']:
        if anomaly['severity'] == "Critical":
            st.error(f"**CRITICAL: {anomaly['inverter']}** | Type: {anomaly['type']} at {anomaly.get('time', 'N/A')} | Reason: {anomaly['details']}")
        elif anomaly['severity'] == "High":
            st.warning(f"**HIGH: {anomaly['inverter']}** | Type: {anomaly['type']} | Details: {anomaly['details']}")
        else:
            st.info(f"**NOTICE: {anomaly['inverter']}** | Type: {anomaly['type']} | Details: {anomaly['details']}")

# Front-end dev notes: 
st.markdown("""
---
*Front-End Dev Note:* 
*To display line charts, point `st.line_chart()` or `plotly` to the processed DataFrames saved in the `./extracted_data/` folder.*
""")

# Optional: Auto-refresh the dashboard every 60 seconds
time.sleep(10)
st.rerun()