[supervisord]
nodaemon=true
user=root

[program:extraction]
command=python extraction_code/vcom_monitor.py
autostart=true
autorestart=true
stderr_logfile=/var/log/extraction.err.log
stdout_logfile=/var/log/extraction.out.log

[program:watchdog]
command=python processor_watchdog.py
autostart=true
autorestart=true
stderr_logfile=/var/log/watchdog.err.log
stdout_logfile=/var/log/watchdog.out.log

[program:dashboard]
command=python dashboard/app.py
autostart=true
autorestart=true
stderr_logfile=/var/log/dashboard.err.log
stdout_logfile=/var/log/dashboard.out.log
